DiplomskiApartmani/GostMVC/Controllers/RezervacijeController.cs
using ApartmaniService.DTO;
using GostMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GostMVC.Controllers
{
    public class RezervacijeController : Controller
    {
        RezervacijeCRUDServis.RezervacijeCRUDServiceClient rezervacijeClient;
        ApartmaniCRUDServis.ApartmaniCRUDServiceClient apartmaniClient;

        public RezervacijeController()
        {
            rezervacijeClient = new RezervacijeCRUDServis.RezervacijeCRUDServiceClient();
            apartmaniClient = new ApartmaniCRUDServis.ApartmaniCRUDServiceClient();
        }
        // GET: Rezervacije
        public ActionResult Index()
        {
            if (Session["GostID"] != null)
            {
                int id = int.Parse(Session["GostID"].ToString());
                IEnumerable<RezervacijaDTO> listaRezervacija = rezervacijeClient.dohvatiRezervacijeZaGosta(id);
                return View(listaRezervacija);
            }
            else
            {
                return RedirectToAction("Prijava", "Gost");
            }
            
        }

        public ActionResult Nova()
        {
            int gostId = int.Parse(Session["GostID"].ToString());
            Common common = new Common();
            RezervacijaViewModel rvm = new RezervacijaViewModel();
            rvm.GostID = gostId;
            rvm.listaApartmana = common.dohvatiApartmane();
            rvm.ApartmanID = 0;
            return View ("Rezervacija",rvm);
        }

        public PartialViewResult Detalji(int id)
        {
            ApartmanDTO apartman = apartmaniClient.dohvatiApartmanID(id);
            return PartialView("Detalji", apartman);
        }

        public ActionResult Otkazi(int id)
        {
            bool otkazano = rezervacijeClient.otkaziRezervaciju(id);
            return RedirectToAction("Index");
        }
    }
}

DiplomskiApartmani/GostMVC/Views/Rezervacije/Detalji.cshtml
@model ApartmaniService.DTO.ApartmanDTO

<h2>Detalji rezervacije</h2>

<div class="form-group">
    @Html.LabelFor(model => model.Grad, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Grad, new { htmlAttributes = new { @class = "form-control" } })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.BrojOsoba, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.BrojOsoba, new { htmlAttributes = new { @class = "form-control" } })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Povrsina, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Povrsina, new { htmlAttributes = new { @class = "form-control" } })
    </div>
</div>

DiplomskiApartmani/GostMVC/Views/Rezervacije/Index.cshtml
@model IEnumerable<ApartmaniService.DTO.RezervacijaDTO>

@{
    ViewBag.Title = "Pregled rezervacija";
}
<script src="@Url.Content("~/Scripts/jquery-3.3.1.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>

<h2>Pregled rezervacija</h2>

<p>
    @Html.ActionLink("Nova rezervacija", "Nova", false)
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NazivApartmana)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Od)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Do)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NazivApartmana)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Od)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Do)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>

            <td>
                @Ajax.ActionLink("Detalji", "Detalji", "Rezervacije", new {id = item.ApartmanID},
                       new AjaxOptions() {
                           HttpMethod = "GET",
                           UpdateTargetId = "Display",
                           InsertionMode = InsertionMode.Replace
                       }) |
                @Html.ActionLink("Otkaži", "Otkazi", new { id = item.RezervacijaID })
            </td>

        </tr>
    }

</table>

<div id="Display">

</div>