DiplomskiApartmani/ApartmaniMVC/Models/ApartmanViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace ApartmaniMVC.Models
{
    public class ApartmanViewModel
    {
        public int ApartmanID { get; set; }
        [DisplayName("Naziv")]
        public string Naziv { get; set; }
        [DisplayName("Broj osoba")]
        public string BrojOsoba { get; set; }
        [DisplayName("Adresa")]
        public string Adresa { get; set; }
        [DisplayName("Grad")]
        public string Grad { get; set; }
        [DisplayName("Površina")]
        public int Povrsina { get; set; }
        [DisplayName("Cijena")]
        public decimal Cijena { get; set; }
    }
}

DiplomskiApartmani/ApartmaniMVC/Models/RezervacijaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ApartmaniMVC.Models
{
    public class RezervacijaViewModel
    {
        public int RezervacijaID { get; set; }
        public int GostID { get; set; }
        public int ApartmanID { get; set; }
        public System.DateTime Od { get; set; }
        public System.DateTime Do { get; set; }
        public short Status { get; set; }
        public string ImeGosta { get; set; }
        public string PrezimeGosta { get; set; }
        public string NazivApartmana { get; set; }
    }
}

DiplomskiApartmani/ApartmaniMVC/Controllers/ApartmaniController.cs
using ApartmaniMVC.Models;
using ApartmaniService.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApartmaniMVC.Controllers
{
    public class ApartmaniController : Controller
    {
        ApartmaniCRUDServis.ApartmaniCRUDServiceClient client;
        RezervacijeCRUDServis.RezervacijeCRUDServiceClient rezervacijeClient;

        public ApartmaniController()
        {
            client = new ApartmaniCRUDServis.ApartmaniCRUDServiceClient();
            rezervacijeClient = new RezervacijeCRUDServis.RezervacijeCRUDServiceClient();
        }
        // GET: Apartmani
        public ActionResult Index()
        {
            IEnumerable<ApartmanDTO> listaApartmana = client.dohvatiListuApartmana();
            return View(listaApartmana);
        }

        public ActionResult Novi()
        {
            ApartmanViewModel noviApartman = new ApartmanViewModel();
            return View(noviApartman);
        }

        public ActionResult Spremi(ApartmanViewModel noviApartman)
        {
            ApartmanDTO apartmanZaUnos = new ApartmanDTO();

            apartmanZaUnos.Naziv = noviApartman.Naziv;
            apartmanZaUnos.Adresa = noviApartman.Adresa;
            apartmanZaUnos.Grad = noviApartman.Grad;
            apartmanZaUnos.Cijena = noviApartman.Cijena;
            apartmanZaUnos.Povrsina = noviApartman.Povrsina;
            apartmanZaUnos.BrojOsoba = noviApartman.BrojOsoba;

            if (noviApartman.ApartmanID != 0)
            {
                apartmanZaUnos.ApartmanID = noviApartman.ApartmanID;
                bool uredivanje = client.urediApartman(apartmanZaUnos);
            }
            else
            {
                bool unos = client.kreirajNoviApartman(apartmanZaUnos);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Uredi(int id)
        {
            ApartmanDTO apartman = client.dohvatiApartmanID(id);
            ApartmanViewModel apartmanZaUredivanje = new ApartmanViewModel();

            apartmanZaUredivanje.Naziv = apartman.Naziv;
            apartmanZaUredivanje.Cijena = apartman.Cijena;
            apartmanZaUredivanje.Povrsina = apartman.Povrsina;
            apartmanZaUredivanje.Grad = apartman.Grad;
            apartmanZaUredivanje.Adresa = apartman.Adresa;
            apartmanZaUredivanje.BrojOsoba = apartman.BrojOsoba;
            apartmanZaUredivanje.ApartmanID = apartman.ApartmanID;

            return View("Novi", apartmanZaUredivanje);
        }

        public PartialViewResult Detalji(int id)
        {
            IEnumerable<RezervacijaDTO> rezervacije = rezervacijeClient.dohvatiRezervacijeZaApartman(id);
            return PartialView("Detalji", rezervacije);
        }
    }
}

DiplomskiApartmani/ApartmaniMVC/Controllers/RezervacijaController.cs
using System.Web.Mvc;
using System.Collections.Generic;
using ApartmaniService.DTO;

namespace ApartmaniMVC.Controllers
{
    public class RezervacijaController : Controller
    {
        RezervacijeCRUDServis.RezervacijeCRUDServiceClient client;

        public RezervacijaController()
        {
            client = new RezervacijeCRUDServis.RezervacijeCRUDServiceClient();
        }
        // GET: Rezervacija
        public ActionResult Index()
        {
            IEnumerable<RezervacijaDTO> listaRezervacija = client.dohvatiNepotvrdeneRezervacije();
            return View(listaRezervacija);
        }

        public ActionResult Potvrdi (int rezervacijaID)
        {
            bool promjena = client.promijeniStatusRezervacije(rezervacijaID, 1);
            return RedirectToAction("Index");
        }

        public ActionResult Odbi(int rezervacijaID)
        {
            bool promjena = client.promijeniStatusRezervacije(rezervacijaID, 2);
            return RedirectToAction("Index");
        }
    }
}

DiplomskiApartmani/ApartmaniMVC/Views/Apartmani/Detalji.cshtml
@model IEnumerable<ApartmaniService.DTO.RezervacijaDTO>

@{
    ViewBag.Title = "Pregled rezervacija";
}

<h2>Rezervacije za apartman</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ImeGosta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrezimeGosta)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Od)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Do)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ImeGosta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PrezimeGosta)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Od)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Do)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>

    </tr>
    }
</table>

DiplomskiApartmani/ApartmaniMVC/Views/Apartmani/Index.cshtml
@model IEnumerable<ApartmaniService.DTO.ApartmanDTO>

@{
    ViewBag.Title = "Index";
}

<script src="@Url.Content("~/Scripts/jquery-3.3.1.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>

<h2>Popis apartmana</h2>
<p>
    @Html.ActionLink("Novi apartman", "Novi", false)
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Adresa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrojOsoba)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cijena)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Povrsina)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Adresa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BrojOsoba)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cijena)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Povrsina)
        </td>
        <td>
            @Html.ActionLink("Uredi", "Uredi", new { id = item.ApartmanID }) |
            @Ajax.ActionLink("Rezervacije", "Detalji", "Apartmani", new {id = item.ApartmanID},
                        new AjaxOptions() {
                            HttpMethod = "GET",
                            UpdateTargetId = "Display",
                            InsertionMode = InsertionMode.Replace
                        })
        </td>
    </tr>
}
</table>

<div id="Display">

</div>

DiplomskiApartmani/ApartmaniMVC/Views/Apartmani/Novi.cshtml
@model ApartmaniMVC.Models.ApartmanViewModel

@{
    ViewBag.Title = "Novi";
}

@if (Model.ApartmanID > 0)
{
    <h2>Uredi apartman</h2>
}
else
{
    <h2>Novi apartman</h2>
}


@using (Html.BeginForm("Spremi", "Apartmani"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @if (Model.ApartmanID > 0)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.ApartmanID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ApartmanID, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.ApartmanID, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ApartmanID)
                </div>
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrojOsoba, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrojOsoba, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrojOsoba, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Povrsina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Povrsina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Povrsina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cijena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cijena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cijena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DiplomskiApartmani/ApartmaniMVC/Views/Apartmani/Uredi.cshtml
@model ApartmaniMVC.Models.ApartmanViewModel

@{
    ViewBag.Title = "Novi";
}

<h2>Uredi</h2>


@using (Html.BeginForm("Spremi", "Apartmani"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ApartmanViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.ApartmanID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApartmanID, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.ApartmanID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrojOsoba, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrojOsoba, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrojOsoba, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Povrsina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Povrsina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Povrsina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cijena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cijena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cijena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DiplomskiApartmani/ApartmaniMVC/Views/Rezervacija/Index.cshtml
@model IEnumerable<ApartmaniService.DTO.RezervacijaDTO>

@{
    ViewBag.Title = "Pregled rezervacija";
}

<h2>Pregled rezervacija</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ImeGosta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrezimeGosta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NazivApartmana)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Od)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Do)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ImeGosta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PrezimeGosta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NazivApartmana)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Od)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Do)
        </td>

        <td>
            @Html.ActionLink("Potvrdi", "Potvrdi", new { rezervacijaID = item.RezervacijaID }) |
            @Html.ActionLink("Odbi", "Odbi", new { rezervacijaID = item.RezervacijaID })
        </td>
    </tr>
}

</table>

DiplomskiApartmani/ApartmaniMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ACME APARTMANI</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ACME APARTMANI", "Index", "Apartmani", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Apartmani", "Index", "Apartmani")</li>
                    <li>@Html.ActionLink("Rezervacije", "Index", "Rezervacija")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ACME APARTMANI</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>