DiplomskiApartmani/GostMVC/Models/GostViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GostMVC.Models
{
    public class GostViewModel
    {
       
        public int GostID { get; set; }
        [Required]
        public string Ime { get; set; }
        [Required]
        public string Prezime { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Sifra { get; set; }
        [Required]
        public string Adresa { get; set; }
        [Required]
        public string Telefon { get; set; }

        public string ErrorMessage { get; set; }
    }
}

DiplomskiApartmani/GostMVC/Controllers/GostController.cs
using ApartmaniService.DTO;
using GostMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace GostMVC.Controllers
{
    public class GostController : Controller
    {
        RegistracijaCRUDServis.RegistracijaCRUDServiceClient client;

        public GostController()
        {
            client = new RegistracijaCRUDServis.RegistracijaCRUDServiceClient();
        }
        // GET: Gost
        public ActionResult Novi()
        {
            GostViewModel gost = new GostViewModel();
            return View(gost);
        }

        public ActionResult Spremi(GostViewModel gost)
        {
            GostDTO gostZaUnos = new GostDTO();

            gostZaUnos.Ime = gost.Ime;
            gostZaUnos.Prezime = gost.Prezime;
            gostZaUnos.Adresa = gost.Adresa;
            gostZaUnos.Telefon = gost.Telefon;
            gostZaUnos.Email = gost.Email;
            gostZaUnos.Sifra = gost.Sifra;

           

            if (gost.GostID > 0)
            {
                gostZaUnos.GostID = gost.GostID;
                bool promjena = client.uredivanjePodataka(gostZaUnos);

                if (promjena)
                {
                    if (Session["GostID"] != null)
                    {
                        Session["Email"] = gost.Email; 
                    }
                    return View("Novi", gost);
                    
                }
                else
                {
                    return View("Novi", gost);
                }
            }
            else
            {
                bool unos = client.novaRegistracija(gostZaUnos);

                if (unos)
                {
                    return View("Prijava");
                }
                else
                {
                    return View("Novi", gost);
                }
            }

           
            
        }

        [HttpPost]
        public ActionResult Prijava(GostViewModel gost)
        {
            GostDTO prijavljeniGost = new GostDTO();

            prijavljeniGost = client.prijava(gost.Email, gost.Sifra);

            if (prijavljeniGost != null)
            {
                Session["GostID"] = prijavljeniGost.GostID;
                Session["Email"] = prijavljeniGost.Email;
                return RedirectToAction("Index", "Apartmani");
            }
            else
            {
                gost.ErrorMessage = "Prijava nije uspjela, pokušajte ponovno.";
                return View("Prijava", gost);
            }
        }

        [HttpGet]
        public ActionResult Prijava()
        {
            GostViewModel gost = new GostViewModel();
            return View("Prijava", gost);
        }

        public ActionResult LogOff(string GostID)
        {
            Session["GostID"] = null;
            Session["Email"] = null;
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Uredi(string GostID)
        {
            GostViewModel gost = new GostViewModel();
            GostDTO gostID = client.gostID(GostID);
            
            if (gostID != null)
            {
                gost.Ime = gostID.Ime;
                gost.Prezime = gostID.Prezime;
                gost.Adresa = gostID.Adresa;
                gost.Email = gostID.Email;
                gost.Telefon = gostID.Telefon;
                gost.Sifra = gostID.Sifra;
                gost.GostID = gostID.GostID;
            }
            return View("Novi", gost);
        }
    }
}

DiplomskiApartmani/GostMVC/Views/Gost/Novi.cshtml
@model GostMVC.Models.GostViewModel

@{
    ViewBag.Title = "Novi";
}

@if (Model.GostID > 0)
{
    <h2>Promjena podataka</h2>
}
else
{
    <h2>Registracija</h2>
}



@using (Html.BeginForm("Spremi", "Gost"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.GostID)


        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sifra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sifra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sifra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

DiplomskiApartmani/GostMVC/Views/Gost/Prijava.cshtml
@model GostMVC.Models.GostViewModel

@{
    ViewBag.Title = "Prijava";
}

<h2>Prijava</h2>

@using (Html.BeginForm("Prijava", "Gost")) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @if (!String.IsNullOrEmpty(Model.ErrorMessage))
    {
        @Html.TextAreaFor(model => model.ErrorMessage, new { @class = "text-danger" })
    }

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sifra, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.Sifra, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Sifra, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Prijavi se" class="btn btn-default" />
        </div>
    </div>
</div>
}